version: '3.6'

services:
  api:
    command: ["npm", "run", "start"]
    environment:
      ENV: dev
      LOG_LEVEL: DEBUG
  db:
    volumes:
    - ./db/init_dev.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080