version: '3.6'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - 80:80
    volumes:
      - ./gateway/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["yarn", "start:prod"]
    volumes:
      - ./api:/usr/src/app
    environment:
      ENV: prod
      DATABASE_HOST: db
      DATABASE_USER: hatsurebals
      DATABASE_PASSWORD: hatsurebals123
      DATABASE_SCHEMA: hatsuportal
      LOG_LEVEL: INFO
      PORT: 3000
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/usr/src/app
  db:
    image: postgres:10.4
    restart: always
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: hatsurebals
      POSTGRES_PASSWORD: hatsurebals123
      POSTGRES_DB: hatsuportal